### ISSUE TITLE
MoipCreditCard.setEncrypter React Native retorna hash null

### ISSUE THREAD

**Issue by welintonInfo** [moip/moip-sdk-js#12]
Bom dia, o hash está retornando nulo, estava funcionando perfeita na semana passada
MoipCreditCard.setEncrypter(RSA, 'react-native')
            .setPubKey(pubKey)
            .setCreditCard({
                number: this.props.card_number,
                cvc: this.props.card_cvc,
                expirationMonth: this.props.card_expirationMonth,
                expirationYear: this.props.card_expirationYear
            })
            .hash()
            .then(
                hash => {
                    console.log(hash) // aqui esta chegando null
                }, err => resolve(false)
            );

**Comment by somentelucas** [comment]
@welintonInfo, vou fechar essa PR, caso você continue tendo erros, por favor mande os valores das variáveis também para eu tentar reproduzir aqui, ok?

Muito obrigado!
