### ISSUE TITLE
Não foi possível descriptografar o hash do cartão

### ISSUE THREAD

**Issue by lucasrohers** [moip/moip-sdk-js#16]

**Comment by somentelucas** [comment]
@lucasrohers, onde você coloca `->setCreditCardHash($hash, $customer)`, o `$hash` está com  valor correto? Se tiver, consegue passar o valor do hash gerado?

Além disso, essa função espera um `$holder` como segundo parâmetro, e não um `$customer`, será que pode ser isso?

**Comment by lucasrohers** [comment]
Olá, não é este o problema amigo.
Se eu pego este hash gerado e passo direto ->setCreditCardHash("TODO O HASH AQUI", $customer) ele funciona normalmente.
O que estou achando que é o problema é que como é uma promise, ele está executando todo o código e não está passando o código correto. Existe na SDK de vocês alguma maneira de esperar essa promise ficar pronta, ou então transformar ela em síncrona?
Além disto, não existe nenhum API online que eu envio os dados do cartão para vocês e vocês me devolvam o hash?

**Comment by somentelucas** [comment]
Oi @lucasrohers, não entendi exatamente qual o problema então, se você consegue passar o hash na sua função `->setCreditCardHash("TODO O HASH AQUI", $customer)` e funciona, não parece ser um problema da SDK.

Existe sim uma maneira de esperar a promise ficar pronta, é justamente o método `.then`:

```
.then(hash => console.log('hash', hash));```

Não existe uma API para envio dos dados do cartão, a criptografia é feita no front-end justamente para evitar que dados de cartões sejam transacionados pela web de forma aberta, portanto ter uma API para isso resultaria nos mesmos problemas de segurança que a SDK tenta evitar.

Vou fechar essa issue, se continuar tendo problemas fique a vontade para reabrir com as evidências, ok?
Abraços!
