### ISSUE TITLE
Ionic 3 Hash com erro

### ISSUE THREAD

**Issue by AAlbertoJr** [moip/moip-sdk-js#9]
Fiz um teste com a rotina de vocês apresentada aqui com o seguinte exemplo:
import jsencrypt from 'jsencrypt';
import { MoipCreditCard } from 'moip-sdk-js';
MoipCreditCard
	.setEncrypter(jsencrypt, 'ionic')
    	.setPubKey(pubKey)
	.setCreditCard({
	    number  : '5555666677778884',
	    cvc     : '123',
	    expirationMonth: '12',
      	    expirationYear : '18'
      }).hash()
.then(hash => console.log('hash', hash));
E apresentou o seguinte erro:
Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
Podem me ajudar???

**Comment by somentelucas** [comment]
@lucasnsborges e @AAlbertoJr, qual versão do Ionic vocês estão utilizando?

**Comment by somentelucas** [comment]
Oi @AAlbertoJr, como você está injetando as dependências nos módulos? O fato de o `.then` não estar funcionando significa que provavelmente o MoipCreditCard não está sendo importado corretamente. Pode mandar o seu arquivo completo?

@lucasnsborges, você tá usando react-native com expo?

**Comment by AAlbertoJr** [comment]
Segue o trecho do codigo! Como disse é apenas um teste do que ta lá!
import { Component } from '@angular/core';import { IonicPage, NavController, NavParams} from 'ionic-angular';import { GatewayPagMProvider } from '../../../providers/gateway-pag/gateway-pag-moip';import jsencrypt from 'jsencrypt';import { MoipCreditCard } from 'moip-sdk-js';
@Component({ selector: 'page-Transf-capture', templateUrl: 'Transf-capture.html', providers:[ GatewayPagMProvider ]})export class TransfCapturePage { headercolor:any; fontcolor:any; logo:any; user: any = {}; private posParams; jsonObj:any; constructor(public navCtrl: NavController, public navParams: NavParams,  private gatewaypagProvider: GatewayPagMProvider, moipCredicard:MoipCreditCard) {

//Encryptlet pubKey="-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr7ESDJNZDDSo2iTv+VWT2aBZeQ2ooyahx8fCoc8pn9Wuhb7XrfTSllM5IuP8fuwUWf29F/a7/0V5Nds6XVr+xt1ZxfdKPiGdJbliOhj+EH7+Ahdc7cXzbCQ4ASeBsp+QeVhjCUHCPy2DZ1UskbDD5K3LNTpjaIasMct0NZowEme9akSUm/zQWj37pBJwfyTtC17YrRyhjWsFHvU9r+m3hDq0E4POYrXMG97H1PvJGsqJ0McCkAF2l8XvXU3EmMq4IhFyJZzlQ4shXMvEcDpepSV6wVj2zpa3gvfzPFTngbIoUvaYPykUTGdMRRbDHvC54QzpkNRnH1CwzM/ZTnMRQQIDAQAB-----END PUBLIC KEY-----";console.log("hash");
moipCredicard  .setEncrypter(jsencrypt, 'ionic')   .setPubKey(pubKey)  .setCreditCard({   number : '5555666677778884',   cvc : '123',   expirationMonth: '12',    expirationYear : '18' }).hash() .then(hash =>console.log(hash));
 ionViewDidLoad() { console.log('ionViewDidLoad AtransmitirPage'); }
}

**Comment by somentelucas** [comment]
@AAlbertoJr, tudo bem?

Aqui tem um exemplo de testes de uma aplicação em ionic 3 funcionando. O hash é gerado e mostrado na tela, você pode dar uma olhadinha? https://github.com/brunoosilva/ionic-3-moip-sdk-js-example

Acredito que seja alguma coias com a maneira que você está fazendo o import.
